version: "3"

services:
  helloworld:
    image: nginx:alpine
    deploy:
      replicas: 0

  bookweb:
    image: 192.168.41.129:9999/bookweb:1.00.01
    ports:
      - "9000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
    deploy:
      replicas: 2

  mysql:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=mydb1234
      - MARIADB_ROOT_PASSWORD=demo1234
      - MARIADB_DATABASE=bookdb
    volumes:
      - "mysqldb:/bitnami"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == manager1]

  mariadb-slave:
    image: bitnami/mariadb:latest
    depends_on:
      - mysql
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=mydb1234
      - MARIADB_MASTER_HOST=mysql
      - MARIADB_MASTER_ROOT_PASSWORD=demo1234
    deploy:
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "9980:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer:latest
    ports:
      - "9990:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  mysqldb:
    external: true
